---
- name: Auditar ComfyUI en cada m치quina y mostrar discrepancias
  hosts: comfyui_vms
  tasks:
    - name: Verificar la versi칩n de ComfyUI
      ansible.builtin.command:
        cmd: "git describe --tags"
        chdir: "/home/superreal/ComfyUI"
      register: comfyui_version

    - name: Mostrar la versi칩n de ComfyUI
      ansible.builtin.debug:
        var: comfyui_version.stdout

    - name: Listar todos los archivos en la carpeta models
      ansible.builtin.find:
        paths: "/home/superreal/ComfyUI/models"
        recurse: yes
      register: model_files

    - name: Mostrar la lista de archivos en models
      ansible.builtin.debug:
        var: model_files.files | map(attribute='path')

    - name: Listar los repositorios de git en las carpetas de custom_nodes
      ansible.builtin.command:
        cmd: "git remote get-url origin"
        chdir: "{{ item.path }}"
      with_items: "{{ custom_node_dirs.files }}"
      when: item.path is directory
      register: custom_node_repos

    - name: Listar las carpetas en custom_nodes
      ansible.builtin.find:
        paths: "/home/superreal/ComfyUI/custom_nodes"
        recurse: no
        file_type: directory
      register: custom_node_dirs

    - name: Mostrar los repositorios de git en nodos personalizados
      ansible.builtin.debug:
        var: custom_node_repos.results | map(attribute='stdout')

    - name: Comparar discrepancias en archivos de modelos entre m치quinas
      ansible.builtin.shell: |
        diff <(echo "{{ model_files.files | map(attribute='path') | join('\n') }}") <(echo "{{ models_fundador.files | map(attribute='path') | join('\n') }}")
      register: model_discrepancy
      when: inventory_hostname != "fundador_vm"

    - name: Mostrar discrepancias en modelos
      ansible.builtin.debug:
        var: model_discrepancy.stdout
      when: model_discrepancy.stdout is defined

    - name: Comparar discrepancias en nodos personalizados
      ansible.builtin.shell: |
        diff <(echo "{{ custom_node_repos.results | map(attribute='stdout') | join('\n') }}") <(echo "{{ custom_nodes_fundador.results | map(attribute='stdout') | join('\n') }}")
      register: node_discrepancy
      when: inventory_hostname != "fundador_vm"

    - name: Mostrar discrepancias en nodos personalizados
      ansible.builtin.debug:
        var: node_discrepancy.stdout
      when: node_discrepancy.stdout is defined
