- name: Auditar ComfyUI en cada máquina y mostrar discrepancias
  hosts: comfyui_vms
  tasks:
    - name: Verificar la versión de ComfyUI
      ansible.builtin.command:
        cmd: "git describe --tags"
        chdir: "/home/superreal/ComfyUI"
      register: comfyui_version

    - name: Mostrar la versión de ComfyUI
      ansible.builtin.debug:
        var: comfyui_version.stdout

    - name: Listar todos los archivos en la carpeta models
      ansible.builtin.find:
        paths: "/home/superreal/ComfyUI/models"
        recurse: yes
      register: model_files

    - name: Mostrar la lista de archivos en models
      ansible.builtin.debug:
        var: model_files.files | map(attribute='path')

    - name: Listar las carpetas en custom_nodes
      ansible.builtin.find:
        paths: "/home/superreal/ComfyUI/custom_nodes"
        recurse: no
        file_type: directory
      register: custom_node_dirs

    - name: Obtener los repositorios de git en las carpetas de custom_nodes
      ansible.builtin.command:
        cmd: "git remote get-url origin"
        chdir: "{{ item.path }}"
      with_items: "{{ custom_node_dirs.files }}"
      when: item.path is directory
      register: custom_node_repos
      ignore_errors: yes

    - name: Mostrar los repositorios de git en nodos personalizados
      ansible.builtin.debug:
        var: custom_node_repos.results | map(attribute='stdout')

    # Reemplazar los comandos diff por una solución usando sets en Ansible
    - name: Crear archivos temporales para comparación de modelos
      when: inventory_hostname != "fundador_vm"
      block:
        - name: Crear lista de archivos actual
          ansible.builtin.set_fact:
            current_models: "{{ model_files.files | map(attribute='path') | list }}"
            reference_models: "{{ hostvars['fundador_vm'].model_files.files | map(attribute='path') | list }}"

        - name: Encontrar diferencias en modelos
          ansible.builtin.set_fact:
            missing_models: "{{ reference_models | difference(current_models) }}"
            extra_models: "{{ current_models | difference(reference_models) }}"

        - name: Mostrar diferencias en modelos
          ansible.builtin.debug:
            msg: |
              Modelos faltantes en {{ inventory_hostname }}:
              {{ missing_models | join('\n') }}
              
              Modelos extra en {{ inventory_hostname }}:
              {{ extra_models | join('\n') }}

    # Similar para nodos personalizados
    - name: Comparar nodos personalizados
      when: inventory_hostname != "fundador_vm"
      block:
        - name: Crear lista de nodos actual
          ansible.builtin.set_fact:
            current_nodes: "{{ custom_node_repos.results | map(attribute='stdout') | select('defined') | list }}"
            reference_nodes: "{{ hostvars['fundador_vm'].custom_node_repos.results | map(attribute='stdout') | select('defined') | list }}"

        - name: Encontrar diferencias en nodos
          ansible.builtin.set_fact:
            missing_nodes: "{{ reference_nodes | difference(current_nodes) }}"
            extra_nodes: "{{ current_nodes | difference(reference_nodes) }}"

        - name: Mostrar diferencias en nodos
          ansible.builtin.debug:
            msg: |
              Nodos faltantes en {{ inventory_hostname }}:
              {{ missing_nodes | join('\n') }}
              
              Nodos extra en {{ inventory_hostname }}:
              {{ extra_nodes | join('\n') }}
