---
# install_comfyui.yml
- name: Instalar y configurar ComfyUI
  hosts: emtpy_vms
  environment:
    DEBIAN_FRONTEND: noninteractive
  vars:
    # Variables de sistema y CUDA
    os_version: "2204"
    os_arch: "x86_64"
    cuda_keyring_version: "1.1-1"
    cuda_version: "12.4"
    pytorch_cuda_version: "12.1"
    
    # Variables de instalación
    base_path: "/home/superreal"
    comfy_path: "{{ base_path }}/ComfyUI"
    models_path: "{{ comfy_path }}/models"
    conda_path: "{{ base_path }}/miniconda3"
    conda_env_name: "comfyenv"
    python_version: "3.10"
    service_user: "superreal"
    gpu_memory: "80"

    # Variables calculadas
    cuda_repo_url: "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu{{ os_version }}/{{ os_arch }}"

  tasks:
    # Limpieza inicial del sistema
    - name: Eliminar drivers NVIDIA existentes
      ansible.builtin.shell: |
        apt-get purge -y nvidia* cuda* --allow-change-held-packages || true
        apt-get autoremove -y || true
      become: yes
      ignore_errors: yes

    - name: Limpiar sistema de paquetes
      ansible.builtin.shell: |
        lsof /var/lib/dpkg/lock* /var/lib/apt/lists/lock /var/cache/apt/archives/lock /var/cache/debconf/*.dat* 2>/dev/null | awk '{print $2}' | xargs kill -9 2>/dev/null || true
        rm -f /var/lib/dpkg/lock* || true
        rm -f /var/lib/apt/lists/lock || true
        rm -f /var/cache/apt/archives/lock || true
        rm -f /var/cache/debconf/*.dat* || true
        sleep 5
        dpkg --configure -a
        apt-get clean
        apt-get update --fix-missing
      become: yes
      ignore_errors: yes

    # Verificación inicial
    - name: Verificar si ya existe una instalación
      ansible.builtin.stat:
        path: "{{ comfy_path }}"
      register: comfy_dir

    - name: Detener si ya existe instalación
      ansible.builtin.fail:
        msg: "Ya existe una instalación en {{ comfy_path }}"
      when: comfy_dir.stat.exists

    # Sistema y drivers
    - name: Actualizar sistema
      ansible.builtin.shell: |
        apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y dist-upgrade
      become: yes

    - name: Instalar dependencias básicas
      ansible.builtin.apt:
        name:
          - wget
          - git
          - libgl1
          - libglib2.0-0
          - ubuntu-drivers-common
          - dkms
          - build-essential
        state: present
        update_cache: yes
      become: yes

    - name: Instalar drivers NVIDIA
      ansible.builtin.shell: |
        DEBIAN_FRONTEND=noninteractive ubuntu-drivers autoinstall
        sleep 5
        systemctl daemon-reload
      become: yes
      
    # CUDA
    - name: Descargar CUDA keyring
      ansible.builtin.get_url:
        url: "{{ cuda_repo_url }}/cuda-keyring_{{ cuda_keyring_version }}_all.deb"
        dest: /tmp/cuda-keyring.deb
      register: cuda_keyring_download
      ignore_errors: yes

    - name: Mostrar error si falla la descarga del keyring
      ansible.builtin.fail:
        msg: |
          Error al descargar CUDA keyring.
          URL: {{ cuda_repo_url }}/cuda-keyring_{{ cuda_keyring_version }}_all.deb
          Verifica:
          - Versión Ubuntu ({{ os_version }})
          - Versión keyring ({{ cuda_keyring_version }})
          - URL repositorio ({{ cuda_repo_url }})
      when: cuda_keyring_download is failed

    - name: Instalar CUDA keyring
      ansible.builtin.apt:
        deb: /tmp/cuda-keyring.deb
      become: yes

    - name: Instalar CUDA Toolkit
      ansible.builtin.apt:
        name: "cuda-toolkit-{{ cuda_version | replace('.', '-') }}"
        state: present
        update_cache: yes
      become: yes

    # Miniconda
    - name: Verificar instalación de Miniconda
      ansible.builtin.stat:
        path: "{{ conda_path }}"
      register: conda_check

    - name: Descargar Miniconda
      ansible.builtin.get_url:
        url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: /tmp/miniconda.sh
        mode: '0755'
      when: not conda_check.stat.exists

    - name: Instalar Miniconda
      ansible.builtin.command:
        cmd: "bash /tmp/miniconda.sh -b -u -p {{ conda_path }}"
        creates: "{{ conda_path }}"
      when: not conda_check.stat.exists

    - name: Configurar Conda
      ansible.builtin.shell:
        cmd: |
          {{ conda_path }}/bin/conda init bash
          {{ conda_path }}/bin/conda create -y -n {{ conda_env_name }} python={{ python_version }}
          source {{ conda_path }}/bin/activate {{ conda_env_name }}
          conda install -y pytorch torchvision torchaudio pytorch-cuda={{ pytorch_cuda_version }} -c pytorch -c nvidia
        executable: /bin/bash

    # Estructura de directorios
    - name: Crear directorios necesarios
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ service_user }}"
        mode: '0755'
      loop:
        - "{{ comfy_path }}"
        - "{{ models_path }}/checkpoints"
        - "{{ models_path }}/clip"
        - "{{ models_path }}/controlnet"
        - "{{ models_path }}/diffusers"
        - "{{ models_path }}/embeddings"
        - "{{ models_path }}/faces"
        - "{{ models_path }}/ipadapter"
        - "{{ models_path }}/loras"
        - "{{ models_path }}/upscale_models"
        - "{{ models_path }}/vae"
        - "{{ comfy_path }}/custom_nodes"
        - "{{ comfy_path }}/output"

    # ComfyUI
    - name: Clonar ComfyUI
      ansible.builtin.git:
        repo: https://github.com/comfyanonymous/ComfyUI.git
        dest: "{{ comfy_path }}"
        version: master

    - name: Instalar requisitos de ComfyUI
      ansible.builtin.shell:
        cmd: |
          source {{ conda_path }}/bin/activate {{ conda_env_name }}
          pip install -r requirements.txt
        args:
          chdir: "{{ comfy_path }}"

    # Configuración y servicio
    - name: Crear configuración de ComfyUI
      ansible.builtin.copy:
        content: |
          extra_model_paths:
            - path: {{ models_path }}
              folder_paths_cfg:
                checkpoints: checkpoints
                clip: clip
                clip_vision: clip_vision
                controlnet: controlnet
                embeddings: embeddings
                loras: loras
                upscale_models: upscale_models
                vae: vae
          virtual_memory: {{ gpu_memory }}
        dest: "{{ comfy_path }}/extra_model_paths.yaml"

    - name: Crear script de inicio
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          source {{ conda_path }}/bin/activate {{ conda_env_name }}
          python {{ comfy_path }}/main.py --listen 0.0.0.0 --port 8188
        dest: "{{ comfy_path }}/start.sh"
        mode: '0755'
        owner: "{{ service_user }}"

    - name: Crear servicio systemd
      ansible.builtin.copy:
        dest: /etc/systemd/system/comfyui.service
        content: |
          [Unit]
          Description=ComfyUI Service
          After=network.target

          [Service]
          Type=simple
          User={{ service_user }}
          Group={{ service_user }}
          WorkingDirectory={{ comfy_path }}
          ExecStart={{ comfy_path }}/start.sh
          Restart=always
          RestartSec=10s

          [Install]
          WantedBy=multi-user.target
      become: yes

    - name: Activar servicio
      ansible.builtin.systemd:
        name: comfyui
        enabled: yes
        state: started
        daemon_reload: yes
      become: yes
