---
- name: Auditar ComfyUI en cada máquina y mostrar discrepancias
  hosts: comfyui_vms
  tasks:
    - name: Verificar la versión de ComfyUI
      ansible.builtin.command:
        cmd: "git describe --tags"
        chdir: "/home/superreal/ComfyUI"
      register: comfyui_version

    - name: Mostrar la versión de ComfyUI
      ansible.builtin.debug:
        var: comfyui_version.stdout

    - name: Listar todos los archivos en la carpeta models
      ansible.builtin.find:
        paths: "/home/superreal/ComfyUI/models"
        recurse: yes
      register: model_files

    - name: Mostrar la lista de archivos en models
      ansible.builtin.debug:
        var: model_files.files | map(attribute='path')

    - name: Listar las carpetas en custom_nodes
      ansible.builtin.find:
        paths: "/home/superreal/ComfyUI/custom_nodes"
        recurse: no
        file_type: directory
      register: custom_node_dirs

    - name: Obtener los repositorios de git en las carpetas de custom_nodes
      ansible.builtin.command:
        cmd: "git remote get-url origin"
        chdir: "{{ item.path }}"
      with_items: "{{ custom_node_dirs.files }}"
      when: item.path is directory
      register: custom_node_repos

    - name: Mostrar los repositorios de git en nodos personalizados
      ansible.builtin.debug:
        var: custom_node_repos.results | map(attribute='stdout')

    - name: Comparar discrepancias en archivos de modelos entre máquinas
      ansible.builtin.shell: |
        diff <(echo "{{ model_files.files | map(attribute='path') | join('\n') }}") <(echo "{{ hostvars['fundador_vm'].model_files.files | map(attribute='path') | join('\n') }}")
      register: model_discrepancy
      when: inventory_hostname != "fundador_vm"

    - name: Mostrar modelos faltantes en comparación con fundador_vm
      ansible.builtin.shell: |
        comm -13 <(echo "{{ hostvars['fundador_vm'].model_files.files | map(attribute='path') | join('\n') }}") <(echo "{{ model_files.files | map(attribute='path') | join('\n') }}")
      register: missing_models
      when: inventory_hostname != "fundador_vm"

    - name: Mostrar modelos que faltan
      ansible.builtin.debug:
        msg: "Modelos faltantes en {{ inventory_hostname }}: {{ missing_models.stdout }}"
      when: missing_models.stdout is defined

    - name: Comparar discrepancias en nodos personalizados entre máquinas
      ansible.builtin.shell: |
        diff <(echo "{{ custom_node_repos.results | map(attribute='stdout') | join('\n') }}") <(echo "{{ hostvars['fundador_vm'].custom_node_repos.results | map(attribute='stdout') | join('\n') }}")
      register: node_discrepancy
      when: inventory_hostname != "fundador_vm"

    - name: Mostrar nodos faltantes en comparación con fundador_vm
      ansible.builtin.shell: |
        comm -13 <(echo "{{ hostvars['fundador_vm'].custom_node_repos.results | map(attribute='stdout') | join('\n') }}") <(echo "{{ custom_node_repos.results | map(attribute='stdout') | join('\n') }}")
      register: missing_nodes
      when: inventory_hostname != "fundador_vm"

    - name: Mostrar nodos que faltan
      ansible.builtin.debug:
        msg: "Nodos faltantes en {{ inventory_hostname }}: {{ missing_nodes.stdout }}"
      when: missing_nodes.stdout is defined
