- name: Auditar ComfyUI en cada máquina y mostrar discrepancias
  hosts: comfyui_vms
  tasks:
    - name: Listar todos los archivos en la carpeta models
      ansible.builtin.find:
        paths: "/home/superreal/ComfyUI/models"
        recurse: yes
      register: model_files

    - name: Crear set consolidado de todos los modelos existentes
      ansible.builtin.set_fact:
        all_models: "{{ ansible_play_hosts | map('extract', hostvars) | map(attribute='model_files') | map(attribute='files') | map('map', attribute='path') | flatten | unique | list }}"

    - name: Encontrar modelos faltantes en cada host
      ansible.builtin.set_fact:
        missing_models: "{{ all_models | difference(model_files.files | map(attribute='path') | list) }}"

    - name: Mostrar modelos faltantes
      ansible.builtin.debug:
        msg: |
          Modelos faltantes en {{ inventory_hostname }}:
          {% for model in missing_models %}
          - {{ model }}
          {% endfor %}
      when: missing_models | length > 0

    - name: Listar las carpetas en custom_nodes
      ansible.builtin.find:
        paths: "/home/superreal/ComfyUI/custom_nodes"
        recurse: no
        file_type: directory
      register: custom_node_dirs

    - name: Crear lista de nombres de carpetas de nodos
      ansible.builtin.set_fact:
        node_folders: "{{ custom_node_dirs.files | map(attribute='path') | map('basename') | list | reject('match', '^__') | list }}"

    - name: Crear set consolidado de todos los nodos existentes
      ansible.builtin.set_fact:
        all_nodes: "{{ ansible_play_hosts | map('extract', hostvars) | map(attribute='node_folders') | flatten | unique | list }}"

    - name: Encontrar nodos faltantes en cada host
      ansible.builtin.set_fact:
        missing_nodes: "{{ all_nodes | difference(node_folders) }}"

    - name: Obtener URLs de git para todos los nodos conocidos
      ansible.builtin.command:
        cmd: "git -C /home/superreal/ComfyUI/custom_nodes/{{ item }} remote get-url origin"
      loop: "{{ all_nodes }}"
      register: all_git_urls
      ignore_errors: yes
      when: all_nodes | length > 0

    - name: Mostrar nodos faltantes con sus URLs
      ansible.builtin.debug:
        msg: |
          Nodos faltantes en {{ inventory_hostname }}:
          {% for node in missing_nodes %}
          - {{ node }}
            URL: {{ all_git_urls.results | selectattr('item', 'equalto', node) | selectattr('rc', 'equalto', 0) | map(attribute='stdout') | list | first | default('URL no disponible') }}
          {% endfor %}
      when: missing_nodes | length > 0
