---
- name: Verificar la versi칩n de ComfyUI en cada m치quina
  hosts: comfyui_vms
  tasks:
    - name: Ejecutar el comando para obtener la versi칩n de ComfyUI
      ansible.builtin.command:
        cmd: "git describe --tags"
        chdir: "/home/superreal/ComfyUI"
      register: comfyui_version

    - name: Mostrar la versi칩n de ComfyUI
      ansible.builtin.debug:
        var: comfyui_version.stdout
