---
- name: Playbook b치sico para testear conectividad y funcionalidad
  hosts: all
  gather_facts: no
  tasks:
    - name: Testear conectividad con el m칩dulo ping
      ansible.builtin.ping:

    - name: Verificar la informaci칩n del sistema
      ansible.builtin.command:
        cmd: uname -a
      register: system_info

    - name: Mostrar la informaci칩n del sistema
      debug:
        var: system_info.stdout
